name: nakama
description: Nakama is an open-source scalable game server that lets you focus
  on building games.
version: 0.1.6
repository: https://github.com/obrunsmann/flutter_nakama
homepage: https://flutter-nakama.gitbook.io

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^4.0.1
  collection: ^1.16.0
  fixnum: ^1.0.0
  flutter:
    sdk: flutter
  grpc: ^3.0.0
  json_annotation: ^4.4.0
  jwt_decoder: ^2.0.1
  logging: ^1.0.2
  meta: ^1.7.0
  protobuf: ^2.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.0
  chopper_generator: ^4.0.5
  faker: ^2.0.0
  flutter_lints: ^2.0.1
  json_serializable: ^6.1.4
  swagger_dart_code_generator: ^2.7.3
  test: ^1.17.5
